# Generated by Django 3.2.7 on 2021-09-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('birth', models.IntegerField(default=0)),
                ('nickname', models.CharField(max_length=20)),
                ('introduce', models.CharField(max_length=50)),
            ],
        ),
    ]
